# Maching Learning with Python

In [2]:
# to use an algorithm, import from scikit-learn via an "estimator"
from sklearn.linear_model import LinearRegression

In [4]:
# instantiate the model
model = LinearRegression(normalize=True)
print(model)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)


In [9]:
# fit model with data (training/test data)
# X - the data, y - the labels
import numpy as np
from sklearn.cross_validation import train_test_split
X = np.arange(10).reshape((5,2))
y = range(5)

In [6]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [8]:
list(y)

[0, 1, 2, 3, 4]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [11]:
X_train

array([[0, 1],
       [4, 5],
       [6, 7]])

In [12]:
X_test

array([[8, 9],
       [2, 3]])

In [13]:
y_train

[0, 2, 3]

In [14]:
y_test

[4, 1]

In [23]:
# fit data onto model (if unsupervised, only fit with X (the data))
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [26]:
# For unsupervised learning model, no training, we use the predict method to predict lables given a data set
predictions = model.predict(X_test)

In [27]:
predictions

array([4., 1.])