### NumPy Arrays

In [1]:
my_list = [1,2,3]

In [4]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2], [2,3], [4,5]]

In [8]:
np.array(my_mat)

array([[1, 2],
       [2, 3],
       [4, 5]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2) # 0-10 with step size of 2

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((2,3)) # pass in tuple to get 2d list

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.linspace(0,5,10) # 10 numbers evenly spaced from 0-5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.eye(3) # generate identity matrix of n dimensions (3 here)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.random.rand(5) # 1D array of 5 random nums

array([0.468313  , 0.69921799, 0.45992155, 0.05701781, 0.84374648])

In [18]:
np.random.rand(5, 5) # 5x5 matrix of random nums

array([[0.18722954, 0.28296032, 0.93838824, 0.02146821, 0.72249494],
       [0.67669501, 0.72253537, 0.75590981, 0.09008868, 0.49454815],
       [0.14589548, 0.4565892 , 0.87263535, 0.52881175, 0.18527822],
       [0.09148818, 0.76897994, 0.05244601, 0.26129142, 0.52843114],
       [0.75036482, 0.4762276 , 0.4742067 , 0.06437104, 0.16870216]])

In [19]:
np.random.randn(2) # random number from standard normal distribution

array([-0.42064061, -0.14355521])

In [20]:
np.random.randint(1,100,2) # 2 random numbers between 1 and 100 

array([50, 57])

In [21]:
arr = np.arange(25)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr = np.random.randint(0,50,10)

In [25]:
ranarr

array([39, 24, 28, 13, 18, 14,  5, 14, 25, 45])

In [26]:
arr.reshape(5,5) # evenly re-distributes array, will throw error if it won't fit new shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
ranarr.max()

45

In [28]:
ranarr.min()

5

In [30]:
ranarr.argmax() # index of max value

9

In [31]:
ranarr.argmin() # index of min value

6

In [34]:
arr.shape # dimension information, no second param if 1D

(25,)

In [35]:
arr.dtype # data type of elements in the array

dtype('int64')

In [36]:
from numpy.random import randint # import to use functions directly from numpy.random

In [37]:
randint(2,10)

2

### NumPy Indexing and Selection