# NumPy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2], [2,3], [4,5]]

In [8]:
np.array(my_mat)

array([[1, 2],
       [2, 3],
       [4, 5]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2) # 0-10 with step size of 2

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((2,3)) # pass in tuple to get 2d list

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.linspace(0,5,10) # 10 numbers evenly spaced from 0-5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.eye(3) # generate identity matrix of n dimensions (3 here)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.random.rand(5) # 1D array of 5 random nums

array([0.468313  , 0.69921799, 0.45992155, 0.05701781, 0.84374648])

In [18]:
np.random.rand(5, 5) # 5x5 matrix of random nums

array([[0.18722954, 0.28296032, 0.93838824, 0.02146821, 0.72249494],
       [0.67669501, 0.72253537, 0.75590981, 0.09008868, 0.49454815],
       [0.14589548, 0.4565892 , 0.87263535, 0.52881175, 0.18527822],
       [0.09148818, 0.76897994, 0.05244601, 0.26129142, 0.52843114],
       [0.75036482, 0.4762276 , 0.4742067 , 0.06437104, 0.16870216]])

In [19]:
np.random.randn(2) # random number from standard normal distribution

array([-0.42064061, -0.14355521])

In [20]:
np.random.randint(1,100,2) # 2 random numbers between 1 and 100 

array([50, 57])

In [21]:
arr = np.arange(25)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr = np.random.randint(0,50,10)

In [25]:
ranarr

array([39, 24, 28, 13, 18, 14,  5, 14, 25, 45])

In [26]:
arr.reshape(5,5) # evenly re-distributes array, will throw error if it won't fit new shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
ranarr.max()

45

In [28]:
ranarr.min()

5

In [30]:
ranarr.argmax() # index of max value

9

In [31]:
ranarr.argmin() # index of min value

6

In [34]:
arr.shape # dimension information, no second param if 1D

(25,)

In [35]:
arr.dtype # data type of elements in the array

dtype('int64')

In [36]:
from numpy.random import randint # import to use functions directly from numpy.random

In [37]:
randint(2,10)

2

# NumPy Indexing and Selection

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [7]:
arr[1:5] # slice notation, give me subarray from index 1 to 5

array([1, 2, 3, 4])

In [8]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [10]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [13]:
arr[0:5] = 100 # assign all values in subarray to 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
arr = np.arange(0,11)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_of_arr = arr[0:6]

In [20]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [21]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [22]:
slice_of_arr[:] = 99

In [23]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [26]:
# note that reassigning this val "broadcasted" it to the oringal array,
# slicing is pointing at orignal obj, not duplicating
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [28]:
arr_copy = arr.copy() # this will do an actual copy

In [29]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [30]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [34]:
arr_copy[:] = 100 # since this is a copy, it will not affect arr when slicing

In [32]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [33]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [35]:
arr_2d = np.array([[5,10,15], [20, 25, 30], [35, 40, 45]])

In [36]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
arr_2d[0][0]

5

In [38]:
arr_2d[0, 0]

5

In [40]:
 arr_2d[:2, 1:] # Of the arrays, grab index 0, 1. Then for each array, grab index 1, 2

array([[10, 15],
       [25, 30]])

In [41]:
arr_2d[1][:]

array([20, 25, 30])

In [42]:
arr = np.arange(1,11)

In [43]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
bool_arr = arr > 5 # makes this comparison against each val in the array and returns the bool

In [46]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [49]:
arr[bool_arr] # returns values that have matching indexes to True vals in bool_arr

array([ 6,  7,  8,  9, 10])

In [51]:
arr[arr > 5] # shorthand

array([ 6,  7,  8,  9, 10])

In [52]:
arr_2d = np.arange(50).reshape(5, 10)

In [53]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [55]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

# NumPy Operations

In [56]:
arr = np.arange(0,11)

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr + arr # applies operation to the two arrays

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [59]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [60]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr + 100 # applies operation on each val in array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [65]:
arr / arr # operations that normally error out only throw a warning here

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [66]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

#### Universal Array Functions (unfunc)

In [67]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [68]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [69]:
np.max(arr)

10

In [70]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])